# Site settings
title: Pedal Driven
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

menu:
  -
    title: "About"
    url: "/about.html"
  -
    title: "Contact"
    url: "/contact.html"
  -
    title: "Interviews"
    url: "/interviews.html"